### ISSUE TITLE
`Eraser.clearAppNotificationsByTag()` not working in iOS

### ISSUE THREAD

**Issue by yohanrw** [Wes1324/eraser#6]
First, let me thank you for this amazing pub.

The code you have is working fine in Android. However it is not the case for iOS.  I am using iOS 15.7 in apple phone and I can confirm `Eraser.clearAppNotificationsByTag()` is not working for iOS anymore. However `clearAllAppNotifications()` does work.

Appreciate your attention on this fix it.

**Comment by ndoyepato** [comment]
Facing the same error

**Comment by Wes1324** [comment]
Hey, I appreciate it's taken me a year and a half to reply so you might not be interested in replying anymore but I've had a look into this and I'm struggling to see the issue.

I've just tested it using the example app included in the repo on an iPhone 11 running iOS 17.4.1 and it seems to be working fine (see attached video).

Can you confirm if this is still is an issue for you? If so, can you share how you are adding the tag to your notifications, in order to rule out that it is an issue with the tags you are using.

Thanks

https://github.com/Wes1324/eraser/assets/25579138/48951787-67ee-4956-a0f7-04210be81fa4

**Comment by Wes1324** [comment]
Closing this for now due to inactivity but feel free to open again if you see fit
